name: Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: "18.17.0"

      - run: npm ci

      - run: npm run lint:prettier:check
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: "22"

      - run: npm ci

      - run: npm run lint:eslint:check
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: "22"
      - run: npm ci
      - run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
